DROP TABLE CATEGORYS;
DROP TABLE MODBUS_PLCS;
DROP TABLE MODBUS_DIGITAL;

--Initial

CREATE TABLE CATEGORYS (ID INT PRIMARY KEY, NAME VARCHAR(100) UNIQUE);

CREATE TABLE MODBUS_PLCS (ID INT PRIMARY KEY, NAME VARCHAR(100) UNIQUE, IP VARCHAR(100) UNIQUE, PORT INT);

CREATE TABLE MODBUS_DIGITAL (ID INT PRIMARY KEY, NAME VARCHAR(100), DESCRIPTION VARCHAR(200), CATEGORY INT NOT NULL, PLC INT NOT NULL, MODBUSADDR INT);
ALTER TABLE MODBUS_DIGITAL ADD CONSTRAINT MODBUS_ID_CATEGORYS FOREIGN KEY (CATEGORY) REFERENCES CATEGORYS(ID);
ALTER TABLE MODBUS_DIGITAL ADD CONSTRAINT MODBUS_ID_PLCS FOREIGN KEY (PLC) REFERENCES MODBUS_PLCS(ID);

INSERT INTO CATEGORYS (ID , NAME) VALUES (1,'Büro 1');
INSERT INTO CATEGORYS (ID , NAME) VALUES (2,'Büro 2');

INSERT INTO MODBUS_PLCS (ID , NAME, IP, PORT) VALUES (1, 'Wago Starterkit', '192.168.1.55', 502);

INSERT INTO MODBUS_DIGITAL (ID, NAME, DESCRIPTION, CATEGORY, PLC, MODBUSADDR) VALUES (1, '%MX2.1', '(Raum -1.02) Gruppe 1', 1, 1, 12321); -- UV1|Beleuchtung|VISU_UV1_51K2
INSERT INTO MODBUS_DIGITAL (ID, NAME, DESCRIPTION, CATEGORY, PLC, MODBUSADDR) VALUES (2, '%MX2.2', '(Raum -1.02) Gruppe 2', 1, 1, 12322); -- UV1|Beleuchtung|VISU_UV1_51K3

INSERT INTO MODBUS_DIGITAL (ID, NAME, DESCRIPTION, CATEGORY, PLC, MODBUSADDR) VALUES (3, '%MX2.3', '(Raum -1.03) Gruppe 1', 2, 1, 12323); -- UV1|Beleuchtung|VISU_UV1_52K3
INSERT INTO MODBUS_DIGITAL (ID, NAME, DESCRIPTION, CATEGORY, PLC, MODBUSADDR) VALUES (4, '%MX2.3', '(Raum -1.03) Gruppe 2', 2, 1, 12324); -- UV1|Beleuchtung|VISU_UV1_52K4
INSERT INTO MODBUS_DIGITAL (ID, NAME, DESCRIPTION, CATEGORY, PLC, MODBUSADDR) VALUES (5, '%MX2.3', '(Raum -1.03) Gruppe 3', 2, 1, 12325); -- UV1|Beleuchtung|VISU_UV1_52K5
INSERT INTO MODBUS_DIGITAL (ID, NAME, DESCRIPTION, CATEGORY, PLC, MODBUSADDR) VALUES (6, '%MX2.3', '(Raum -1.03) Gruppe 4', 2, 1, 12326); -- UV1|Beleuchtung|VISU_UV1_52K6
